name: publish
  
on: [push]

env:
  IMAGE_NAME: cookiecutter-cli
  IMAGE_TAG: ${{ github.sha }}

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
            docker build . --tag ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker run ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker push ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest